class Autogenerated {
  bool? success;
  int? code;
  String? message;
  List<Res>? res;

  Autogenerated({this.success, this.code, this.message, this.res});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    code = json['code'];
    message = json['message'];
    if (json['res'] != null) {
      res = <Res>[];
      json['res'].forEach((v) {
        res!.add(new Res.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.res != null) {
      data['res'] = this.res!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Res {
  int? id;
  int? customerId;
  String? category;
  String? businessName;
  String? phone;
  String? email;
  String? website;
  Null? state;
  Null? city;
  Null? instagram;
  Null? facebook;
  Null? youtube;
  Null? linkedin;
  Null? twitter;
  String? createdAt;
  String? updatedAt;
  String? image;
  String? status;
  String? whatsapp;
  String? address;

  Res(
      {this.id,
      this.customerId,
      this.category,
      this.businessName,
      this.phone,
      this.email,
      this.website,
      this.state,
      this.city,
      this.instagram,
      this.facebook,
      this.youtube,
      this.linkedin,
      this.twitter,
      this.createdAt,
      this.updatedAt,
      this.image,
      this.status,
      this.whatsapp,
      this.address});

  Res.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    customerId = json['customer_id'];
    category = json['category'];
    businessName = json['business_name'];
    phone = json['phone'];
    email = json['email'];
    website = json['website'];
    state = json['state'];
    city = json['city'];
    instagram = json['instagram'];
    facebook = json['facebook'];
    youtube = json['youtube'];
    linkedin = json['linkedin'];
    twitter = json['twitter'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    image = json['image'];
    status = json['status'];
    whatsapp = json['whatsapp'];
    address = json['address'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['customer_id'] = this.customerId;
    data['category'] = this.category;
    data['business_name'] = this.businessName;
    data['phone'] = this.phone;
    data['email'] = this.email;
    data['website'] = this.website;
    data['state'] = this.state;
    data['city'] = this.city;
    data['instagram'] = this.instagram;
    data['facebook'] = this.facebook;
    data['youtube'] = this.youtube;
    data['linkedin'] = this.linkedin;
    data['twitter'] = this.twitter;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['image'] = this.image;
    data['status'] = this.status;
    data['whatsapp'] = this.whatsapp;
    data['address'] = this.address;
    return data;
  }
}
