class Autogenerated {
  bool? success;
  int? code;
  String? message;
  List<Res>? res;

  Autogenerated({this.success, this.code, this.message, this.res});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    code = json['code'];
    message = json['message'];
    if (json['res'] != null) {
      res = <Res>[];
      json['res'].forEach((v) {
        res!.add(new Res.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.res != null) {
      data['res'] = this.res!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Res {
  int? framesId;
  String? frameName;
  String? img;
  String? customerNameHeight;
  String? customerNameWidth;
  String? bussinessMarginLeft;
  String? bussinessMarginRight;
  String? bussinessPaddingLeft;
  String? bussinessPaddingRight;
  String? bussinessNameHeight;
  String? bussinessNameWidth;
  String? mobileHeight;
  String? mobileWidth;
  String? mobileMarginLeft;
  String? mobileMarginRight;
  String? mobilePaddingLeft;
  String? mobilePaddingRight;
  String? websiteHeight;
  String? websiteWidth;
  String? websiteMarginLeft;
  String? websiteMarginRight;
  String? websitePaddingLeft;
  String? websitePaddingRight;
  String? logoHeight;
  String? logoWidth;
  String? actualFrameSize;
  String? status;
  String? createdDate;
  String? updatedDate;
  String? emailHeight;
  String? emailWidth;
  String? emailMarginLeft;
  String? emailMarginRight;
  String? emailPaddingLeft;
  String? emailPaddingRight;
  String? addressHeight;
  String? addressWidth;
  String? addressMarginLeft;
  String? addressMarginRight;
  String? addressPaddingLeft;
  String? addressPaddingRight;
  String? iconSize;
  String? mobile;
  String? website;
  String? email;
  String? location;

  Res(
      {this.framesId,
      this.frameName,
      this.img,
      this.customerNameHeight,
      this.customerNameWidth,
      this.bussinessMarginLeft,
      this.bussinessMarginRight,
      this.bussinessPaddingLeft,
      this.bussinessPaddingRight,
      this.bussinessNameHeight,
      this.bussinessNameWidth,
      this.mobileHeight,
      this.mobileWidth,
      this.mobileMarginLeft,
      this.mobileMarginRight,
      this.mobilePaddingLeft,
      this.mobilePaddingRight,
      this.websiteHeight,
      this.websiteWidth,
      this.websiteMarginLeft,
      this.websiteMarginRight,
      this.websitePaddingLeft,
      this.websitePaddingRight,
      this.logoHeight,
      this.logoWidth,
      this.actualFrameSize,
      this.status,
      this.createdDate,
      this.updatedDate,
      this.emailHeight,
      this.emailWidth,
      this.emailMarginLeft,
      this.emailMarginRight,
      this.emailPaddingLeft,
      this.emailPaddingRight,
      this.addressHeight,
      this.addressWidth,
      this.addressMarginLeft,
      this.addressMarginRight,
      this.addressPaddingLeft,
      this.addressPaddingRight,
      this.iconSize,
      this.mobile,
      this.website,
      this.email,
      this.location});

  Res.fromJson(Map<String, dynamic> json) {
    framesId = json['frames_id'];
    frameName = json['frame_name'];
    img = json['img'];
    customerNameHeight = json['customer_name_height'];
    customerNameWidth = json['customer_name_width'];
    bussinessMarginLeft = json['bussiness_margin_left'];
    bussinessMarginRight = json['bussiness_margin_right'];
    bussinessPaddingLeft = json['bussiness_padding_left'];
    bussinessPaddingRight = json['bussiness_padding_right'];
    bussinessNameHeight = json['bussiness_name_height'];
    bussinessNameWidth = json['bussiness_name_width'];
    mobileHeight = json['mobile_height'];
    mobileWidth = json['mobile_width'];
    mobileMarginLeft = json['mobile_margin_left'];
    mobileMarginRight = json['mobile_margin_right'];
    mobilePaddingLeft = json['mobile_padding_left'];
    mobilePaddingRight = json['mobile_padding_right'];
    websiteHeight = json['website_height'];
    websiteWidth = json['website_width'];
    websiteMarginLeft = json['website_margin_left'];
    websiteMarginRight = json['website_margin_right'];
    websitePaddingLeft = json['website_padding_left'];
    websitePaddingRight = json['website_padding_right'];
    logoHeight = json['logo_height'];
    logoWidth = json['logo_width'];
    actualFrameSize = json['actual_frame_size'];
    status = json['status'];
    createdDate = json['created_date'];
    updatedDate = json['updated_date'];
    emailHeight = json['email_height'];
    emailWidth = json['email_width'];
    emailMarginLeft = json['email_margin_left'];
    emailMarginRight = json['email_margin_right'];
    emailPaddingLeft = json['email_padding_left'];
    emailPaddingRight = json['email_padding_right'];
    addressHeight = json['address_height'];
    addressWidth = json['address_width'];
    addressMarginLeft = json['address_margin_left'];
    addressMarginRight = json['address_margin_right'];
    addressPaddingLeft = json['address_padding_left'];
    addressPaddingRight = json['address_padding_right'];
    iconSize = json['icon_size'];
    mobile = json['mobile'];
    website = json['website'];
    email = json['email'];
    location = json['location'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['frames_id'] = this.framesId;
    data['frame_name'] = this.frameName;
    data['img'] = this.img;
    data['customer_name_height'] = this.customerNameHeight;
    data['customer_name_width'] = this.customerNameWidth;
    data['bussiness_margin_left'] = this.bussinessMarginLeft;
    data['bussiness_margin_right'] = this.bussinessMarginRight;
    data['bussiness_padding_left'] = this.bussinessPaddingLeft;
    data['bussiness_padding_right'] = this.bussinessPaddingRight;
    data['bussiness_name_height'] = this.bussinessNameHeight;
    data['bussiness_name_width'] = this.bussinessNameWidth;
    data['mobile_height'] = this.mobileHeight;
    data['mobile_width'] = this.mobileWidth;
    data['mobile_margin_left'] = this.mobileMarginLeft;
    data['mobile_margin_right'] = this.mobileMarginRight;
    data['mobile_padding_left'] = this.mobilePaddingLeft;
    data['mobile_padding_right'] = this.mobilePaddingRight;
    data['website_height'] = this.websiteHeight;
    data['website_width'] = this.websiteWidth;
    data['website_margin_left'] = this.websiteMarginLeft;
    data['website_margin_right'] = this.websiteMarginRight;
    data['website_padding_left'] = this.websitePaddingLeft;
    data['website_padding_right'] = this.websitePaddingRight;
    data['logo_height'] = this.logoHeight;
    data['logo_width'] = this.logoWidth;
    data['actual_frame_size'] = this.actualFrameSize;
    data['status'] = this.status;
    data['created_date'] = this.createdDate;
    data['updated_date'] = this.updatedDate;
    data['email_height'] = this.emailHeight;
    data['email_width'] = this.emailWidth;
    data['email_margin_left'] = this.emailMarginLeft;
    data['email_margin_right'] = this.emailMarginRight;
    data['email_padding_left'] = this.emailPaddingLeft;
    data['email_padding_right'] = this.emailPaddingRight;
    data['address_height'] = this.addressHeight;
    data['address_width'] = this.addressWidth;
    data['address_margin_left'] = this.addressMarginLeft;
    data['address_margin_right'] = this.addressMarginRight;
    data['address_padding_left'] = this.addressPaddingLeft;
    data['address_padding_right'] = this.addressPaddingRight;
    data['icon_size'] = this.iconSize;
    data['mobile'] = this.mobile;
    data['website'] = this.website;
    data['email'] = this.email;
    data['location'] = this.location;
    return data;
  }
}
